// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_ROOT_H
#define __CPP_GUEST_BINDINGS_ROOT_H
#include <cstdint>
#include <utility>
#include <string_view>
#include <expected>
#include <optional>
#include <cassert>
#include <variant>
#include <tuple>
#include "wit.h"
namespace wasi {
  namespace io {
    namespace poll {
      class Pollable;
      class Pollable : public wit::ResourceImportBase{

        public:

        ~Pollable();
        bool Ready() const;
        void Block() const;
        Pollable(wit::ResourceImportBase &&);
        Pollable(Pollable&&) = default;
        Pollable& operator=(Pollable&&) = default;
      };

      wit::vector<uint32_t> Poll(std::span<std::reference_wrapper<const Pollable> const> in);
    }
  }
  namespace clocks {
    namespace monotonic_clock {
      using Pollable = io::poll::Pollable;
      using Instant = uint64_t;
      using Duration = uint64_t;
      uint64_t Now();
      uint64_t Resolution();
      io::poll::Pollable SubscribeInstant(uint64_t when);
      io::poll::Pollable SubscribeDuration(uint64_t when);
    }
    namespace wall_clock {
      struct Datetime {
        uint64_t seconds;
        uint32_t nanoseconds;
      };
      Datetime Now();
      Datetime Resolution();
    }
  }
  namespace random {
    namespace random {
      wit::vector<uint8_t> GetRandomBytes(uint64_t len);
      uint64_t GetRandomU64();
    }
  }
  namespace io {
    namespace error {
      class Error;
      class Error : public wit::ResourceImportBase{

        public:

        ~Error();
        wit::string ToDebugString() const;
        Error(wit::ResourceImportBase &&);
        Error(Error&&) = default;
        Error& operator=(Error&&) = default;
      };

    }
    namespace streams {
      class InputStream;
      class OutputStream;
      using Error = error::Error;
      using Pollable = poll::Pollable;

      struct StreamError {
        struct LastOperationFailed { error::Error value; };
        struct Closed {};
        std::variant<LastOperationFailed, Closed> variants;
      };

      class InputStream : public wit::ResourceImportBase{

        public:

        ~InputStream();
        std::expected<wit::vector<uint8_t>, StreamError> Read(uint64_t len) const;
        std::expected<wit::vector<uint8_t>, StreamError> BlockingRead(uint64_t len) const;
        std::expected<uint64_t, StreamError> Skip(uint64_t len) const;
        std::expected<uint64_t, StreamError> BlockingSkip(uint64_t len) const;
        poll::Pollable Subscribe() const;
        InputStream(wit::ResourceImportBase &&);
        InputStream(InputStream&&) = default;
        InputStream& operator=(InputStream&&) = default;
      };

      class OutputStream : public wit::ResourceImportBase{

        public:

        ~OutputStream();
        std::expected<uint64_t, StreamError> CheckWrite() const;
        std::expected<void, StreamError> Write(std::span<uint8_t const> contents) const;
        std::expected<void, StreamError> BlockingWriteAndFlush(std::span<uint8_t const> contents) const;
        std::expected<void, StreamError> Flush() const;
        std::expected<void, StreamError> BlockingFlush() const;
        poll::Pollable Subscribe() const;
        std::expected<void, StreamError> WriteZeroes(uint64_t len) const;
        std::expected<void, StreamError> BlockingWriteZeroesAndFlush(uint64_t len) const;
        std::expected<uint64_t, StreamError> Splice(std::reference_wrapper<const streams::InputStream> src, uint64_t len) const;
        std::expected<uint64_t, StreamError> BlockingSplice(std::reference_wrapper<const streams::InputStream> src, uint64_t len) const;
        OutputStream(wit::ResourceImportBase &&);
        OutputStream(OutputStream&&) = default;
        OutputStream& operator=(OutputStream&&) = default;
      };
    }
  }
  namespace cli {
    namespace stderr_ {
      using OutputStream = io::streams::OutputStream;
      io::streams::OutputStream GetStderr();
    }
    namespace environment {
      wit::vector<std::tuple<wit::string, wit::string>> GetEnvironment();
      wit::vector<wit::string> GetArguments();
      std::optional<wit::string> InitialCwd();
    }
    namespace exit {
      void Exit(std::expected<void, wit::Void> status);
    }
  }
  namespace http {
    namespace types {
      class Fields;
      class IncomingRequest;
      class IncomingBody;
      class OutgoingRequest;
      class OutgoingBody;
      class ResponseOutparam;
      class OutgoingResponse;
      class IncomingResponse;
      class FutureIncomingResponse;
      class RequestOptions;
      class FutureTrailers;
      using InputStream = io::streams::InputStream;
      using OutputStream = io::streams::OutputStream;
      using Pollable = io::poll::Pollable;
      using IoError = io::error::Error;
      using Duration = uint64_t;
      using FieldKey = wit::string;
      using FieldName = wit::string;

      struct HeaderError {
        struct InvalidSyntax {};
        struct Forbidden {};
        struct Immutable {};
        std::variant<InvalidSyntax, Forbidden, Immutable> variants;
      };
      struct Method {
        struct Get {};
        struct Head {};
        struct Post {};
        struct Put {};
        struct Delete {};
        struct Connect {};
        struct Options {};
        struct Trace {};
        struct Patch {};
        struct Other { wit::string value; };
        std::variant<Get, Head, Post, Put, Delete, Connect, Options, Trace, Patch, Other> variants;
      };
      struct Scheme {
        struct Http {};
        struct Https {};
        struct Other { wit::string value; };
        std::variant<Http, Https, Other> variants;
      };

      class Fields : public wit::ResourceImportBase{

        public:

        ~Fields();
        Fields();
        static std::expected<Fields, HeaderError> FromList(std::span<std::tuple<std::string_view, std::span<uint8_t const>> const> entries);
        wit::vector<wit::vector<uint8_t>> Get(std::string_view name) const;
        bool Has(std::string_view name) const;
        std::expected<void, HeaderError> Set(std::string_view name, std::span<std::span<uint8_t const> const> value) const;
        std::expected<void, HeaderError> Delete(std::string_view name) const;
        std::expected<void, HeaderError> Append(std::string_view name, std::span<uint8_t const> value) const;
        wit::vector<std::tuple<wit::string, wit::vector<uint8_t>>> Entries() const;
        Fields Clone() const;
        Fields(wit::ResourceImportBase &&);
        Fields(Fields&&) = default;
        Fields& operator=(Fields&&) = default;
      };

      class IncomingRequest : public wit::ResourceImportBase{

        public:

        ~IncomingRequest();
        types::Method Method() const;
        std::optional<wit::string> PathWithQuery() const;
        std::optional<types::Scheme> Scheme() const;
        std::optional<wit::string> Authority() const;
        Fields Headers() const;
        std::expected<IncomingBody, wit::Void> Consume() const;
        IncomingRequest(wit::ResourceImportBase &&);
        IncomingRequest(IncomingRequest&&) = default;
        IncomingRequest& operator=(IncomingRequest&&) = default;
      };

      using Headers = Fields;
      class IncomingBody : public wit::ResourceImportBase{

        public:

        ~IncomingBody();
        std::expected<io::streams::InputStream, wit::Void> Stream() const;
        static FutureTrailers Finish(types::IncomingBody&& this_);
        IncomingBody(wit::ResourceImportBase &&);
        IncomingBody(IncomingBody&&) = default;
        IncomingBody& operator=(IncomingBody&&) = default;
      };

      class OutgoingRequest : public wit::ResourceImportBase{

        public:

        ~OutgoingRequest();
        OutgoingRequest(types::Fields&& headers);
        std::expected<OutgoingBody, wit::Void> Body() const;
        types::Method Method() const;
        std::expected<void, wit::Void> SetMethod(types::Method method) const;
        std::optional<wit::string> PathWithQuery() const;
        std::expected<void, wit::Void> SetPathWithQuery(std::optional<std::string_view> path_with_query) const;
        std::optional<types::Scheme> Scheme() const;
        std::expected<void, wit::Void> SetScheme(std::optional<types::Scheme> scheme) const;
        std::optional<wit::string> Authority() const;
        std::expected<void, wit::Void> SetAuthority(std::optional<std::string_view> authority) const;
        Fields Headers() const;
        OutgoingRequest(wit::ResourceImportBase &&);
        OutgoingRequest(OutgoingRequest&&) = default;
        OutgoingRequest& operator=(OutgoingRequest&&) = default;
      };

      struct DnsErrorPayload {
        std::optional<wit::string> rcode;
        std::optional<uint16_t> info_code;
      };
      struct TlsAlertReceivedPayload {
        std::optional<uint8_t> alert_id;
        std::optional<wit::string> alert_message;
      };
      struct FieldSizePayload {
        std::optional<wit::string> field_name;
        std::optional<uint32_t> field_size;
      };
      struct ErrorCode {
        struct DnsTimeout {};
        struct DnsError { types::DnsErrorPayload value; };
        struct DestinationNotFound {};
        struct DestinationUnavailable {};
        struct DestinationIpProhibited {};
        struct DestinationIpUnroutable {};
        struct ConnectionRefused {};
        struct ConnectionTerminated {};
        struct ConnectionTimeout {};
        struct ConnectionReadTimeout {};
        struct ConnectionWriteTimeout {};
        struct ConnectionLimitReached {};
        struct TlsProtocolError {};
        struct TlsCertificateError {};
        struct TlsAlertReceived { types::TlsAlertReceivedPayload value; };
        struct HttpRequestDenied {};
        struct HttpRequestLengthRequired {};
        struct HttpRequestBodySize { std::optional<uint64_t> value; };
        struct HttpRequestMethodInvalid {};
        struct HttpRequestUriInvalid {};
        struct HttpRequestUriTooLong {};
        struct HttpRequestHeaderSectionSize { std::optional<uint32_t> value; };
        struct HttpRequestHeaderSize { std::optional<types::FieldSizePayload> value; };
        struct HttpRequestTrailerSectionSize { std::optional<uint32_t> value; };
        struct HttpRequestTrailerSize { types::FieldSizePayload value; };
        struct HttpResponseIncomplete {};
        struct HttpResponseHeaderSectionSize { std::optional<uint32_t> value; };
        struct HttpResponseHeaderSize { types::FieldSizePayload value; };
        struct HttpResponseBodySize { std::optional<uint64_t> value; };
        struct HttpResponseTrailerSectionSize { std::optional<uint32_t> value; };
        struct HttpResponseTrailerSize { types::FieldSizePayload value; };
        struct HttpResponseTransferCoding { std::optional<wit::string> value; };
        struct HttpResponseContentCoding { std::optional<wit::string> value; };
        struct HttpResponseTimeout {};
        struct HttpUpgradeFailed {};
        struct HttpProtocolError {};
        struct LoopDetected {};
        struct ConfigurationError {};
        struct InternalError { std::optional<wit::string> value; };
        std::variant<DnsTimeout, DnsError, DestinationNotFound, DestinationUnavailable, DestinationIpProhibited, DestinationIpUnroutable, ConnectionRefused, ConnectionTerminated, ConnectionTimeout, ConnectionReadTimeout, ConnectionWriteTimeout, ConnectionLimitReached, TlsProtocolError, TlsCertificateError, TlsAlertReceived, HttpRequestDenied, HttpRequestLengthRequired, HttpRequestBodySize, HttpRequestMethodInvalid, HttpRequestUriInvalid, HttpRequestUriTooLong, HttpRequestHeaderSectionSize, HttpRequestHeaderSize, HttpRequestTrailerSectionSize, HttpRequestTrailerSize, HttpResponseIncomplete, HttpResponseHeaderSectionSize, HttpResponseHeaderSize, HttpResponseBodySize, HttpResponseTrailerSectionSize, HttpResponseTrailerSize, HttpResponseTransferCoding, HttpResponseContentCoding, HttpResponseTimeout, HttpUpgradeFailed, HttpProtocolError, LoopDetected, ConfigurationError, InternalError> variants;
      };

      class OutgoingBody : public wit::ResourceImportBase{

        public:

        ~OutgoingBody();
        std::expected<io::streams::OutputStream, wit::Void> Write() const;
        static std::expected<void, ErrorCode> Finish(types::OutgoingBody&& this_, std::optional<types::Fields> trailers);
        OutgoingBody(wit::ResourceImportBase &&);
        OutgoingBody(OutgoingBody&&) = default;
        OutgoingBody& operator=(OutgoingBody&&) = default;
      };

      class ResponseOutparam : public wit::ResourceImportBase{

        public:

        ~ResponseOutparam();
        static void Set(types::ResponseOutparam&& param, std::expected<types::OutgoingResponse, types::ErrorCode> response);
        ResponseOutparam(wit::ResourceImportBase &&);
        ResponseOutparam(ResponseOutparam&&) = default;
        ResponseOutparam& operator=(ResponseOutparam&&) = default;
      };

      class OutgoingResponse : public wit::ResourceImportBase{

        public:

        ~OutgoingResponse();
        OutgoingResponse(types::Fields&& headers);
        uint16_t StatusCode() const;
        std::expected<void, wit::Void> SetStatusCode(uint16_t status_code) const;
        Fields Headers() const;
        std::expected<OutgoingBody, wit::Void> Body() const;
        OutgoingResponse(wit::ResourceImportBase &&);
        OutgoingResponse(OutgoingResponse&&) = default;
        OutgoingResponse& operator=(OutgoingResponse&&) = default;
      };

      class IncomingResponse : public wit::ResourceImportBase{

        public:

        ~IncomingResponse();
        uint16_t Status() const;
        Fields Headers() const;
        std::expected<IncomingBody, wit::Void> Consume() const;
        IncomingResponse(wit::ResourceImportBase &&);
        IncomingResponse(IncomingResponse&&) = default;
        IncomingResponse& operator=(IncomingResponse&&) = default;
      };

      using StatusCode = uint16_t;
      using Trailers = Fields;
      class FutureIncomingResponse : public wit::ResourceImportBase{

        public:

        ~FutureIncomingResponse();
        io::poll::Pollable Subscribe() const;
        std::optional<std::expected<std::expected<IncomingResponse, ErrorCode>, wit::Void>> Get() const;
        FutureIncomingResponse(wit::ResourceImportBase &&);
        FutureIncomingResponse(FutureIncomingResponse&&) = default;
        FutureIncomingResponse& operator=(FutureIncomingResponse&&) = default;
      };

      class RequestOptions : public wit::ResourceImportBase{

        public:

        ~RequestOptions();
        RequestOptions();
        std::optional<uint64_t> ConnectTimeout() const;
        std::expected<void, wit::Void> SetConnectTimeout(std::optional<uint64_t> duration) const;
        std::optional<uint64_t> FirstByteTimeout() const;
        std::expected<void, wit::Void> SetFirstByteTimeout(std::optional<uint64_t> duration) const;
        std::optional<uint64_t> BetweenBytesTimeout() const;
        std::expected<void, wit::Void> SetBetweenBytesTimeout(std::optional<uint64_t> duration) const;
        RequestOptions(wit::ResourceImportBase &&);
        RequestOptions(RequestOptions&&) = default;
        RequestOptions& operator=(RequestOptions&&) = default;
      };

      class FutureTrailers : public wit::ResourceImportBase{

        public:

        ~FutureTrailers();
        io::poll::Pollable Subscribe() const;
        std::optional<std::expected<std::expected<std::optional<Fields>, ErrorCode>, wit::Void>> Get() const;
        FutureTrailers(wit::ResourceImportBase &&);
        FutureTrailers(FutureTrailers&&) = default;
        FutureTrailers& operator=(FutureTrailers&&) = default;
      };

      std::optional<ErrorCode> HttpErrorCode(std::reference_wrapper<const io::error::Error> err_);
    }
    namespace outgoing_handler {
      using OutgoingRequest = types::OutgoingRequest;
      using RequestOptions = types::RequestOptions;
      using FutureIncomingResponse = types::FutureIncomingResponse;
      using ErrorCode = types::ErrorCode;
      std::expected<types::FutureIncomingResponse, types::ErrorCode> Handle(types::OutgoingRequest&& request, std::optional<types::RequestOptions> options);
      // export_interface Interface(Id { idx: 11 })
    }
  }
}
namespace exports {
  namespace wasi {
    namespace http {
      namespace incoming_handler {
        using IncomingRequest = ::wasi::http::types::IncomingRequest;
        using ResponseOutparam = ::wasi::http::types::ResponseOutparam;
        void Handle(::wasi::http::types::IncomingRequest&& request, ::wasi::http::types::ResponseOutparam&& response_out);
      }
    }
  }
}

#endif
